### ISSUE TITLE
Close datepicker in IE

### ISSUE THREAD

**Issue by morojosa** [glad/glDatePicker#1]
When you click in document. or window. datepicker not close.

**Comment by eddievlagea** [comment]
This issue is only in IE7 and IE8. In IE9 the datepicker is closed when you click outside.

**Comment by glad** [comment]
Thanks for the feedback unfortunately I have not tested it against IE7 or IE8.

**Comment by Yahasana** [comment]
It may be problem from `***.apply(self)` or `***.apply($(this))`
they should be `***.apply(self[0])` or `***.apply(this)`

**Comment by steveruiz** [comment]
this is fixed if the following change is made:

``` javascript
// Bind click elsewhere to hide
$(document).bind("click", function(e)
{
    methods.hide.apply(self);
});
```

the only change is binding the click on the document object instead of the window object.

**Comment by glad** [comment]
Thanks for the suggestion.  I've applied this to the latest release.
