### ISSUE TITLE
Add ability to select dates in next and previous month

### ISSUE THREAD

**Issue by jeromegn** [glad/glDatePicker#12]
Perhaps as an optional setting, but it should be done. For the user experience's sake.

**Here's a thought on how to do this:**
- Remove the `.noday` class for prev or next months' dates
- Store in each `td`s (of dates) `data("month")` property, the month of the date
- When updating the date field, take into account the selected `td`'s month

**Comment by glad** [comment]
This will be resolved in the next update. Thanks for the suggestion.

**Comment by glad** [comment]
This is addressed in the next build coming out soon.

If the previous or next months have a selectable date, clicking on that date will update the calendar to that date's month.
