### ISSUE TITLE
Two gldatepicker

### ISSUE THREAD

**Issue by sjscosta** [glad/glDatePicker#13]
I have two gldatepicker and I would like that the second calendar the startDate start with the date selected on the firt calendar. It's possible?

**Comment by glad** [comment]
Yes this is possible however there may be an issue in this particular version.  See this example here:
http://jsfiddle.net/4CPMw/

I am working on some changes for a new release and will look into this issue.

**Comment by glad** [comment]
This is addressed in the next build coming out soon.

You can now set the calendar to a specific month (when date is selected in another).

Gist of the code below:

```
$('#date1').glDatePicker(
{
    onChange: function(target, date, data) {
        // Set the first date on the 2nd calendar to the one that was picked in the 1st calendar
        // NOTE: the date part will be set to the 1st of the month by the setFirstDate function
        $('#date2').glDatePicker('setFirstDate', date);

        // Update the 2nd calendar
        $('#date2').glDatePicker('update');
    }
});
```
