### ISSUE TITLE
Uncaught TypeError: Cannot read property 'showAlways' of undefined

### ISSUE THREAD

**Issue by fezfez** [glad/glDatePicker#15]
Hi,

I found this issue with your script : "Uncaught TypeError: Cannot read property 'showAlways' of undefined. "

This error appear when a div (witch contain a gldatepicker) is reload by ajax, and then the calendar is created once again.
When i click around the gldatepicker for close it the error appear.

It seems that the jquery's data function return "undefined" on line 113, on hide method.

I do a quick and dirty fix, maybe it can help you to understand the bug :

hide: function()
{

```
if($(this).length)
{
    var s = $(this).data("settings");

    // prevent the bug here
    if(s === undefined) {
        $(this).slideUp(200);
        $(this).removeClass("_gldp");
        // Hide if not showing always
    } else if(!s.showAlways)
    {
        // Hide the calendar and remove class from target
        $("#"+s.calId).slideUp(200);
        $(this).removeClass("_gldp");
    }
}
```

}

Thanks.

**Comment by glad** [comment]
Thanks Steph!  I will definitely test this out and put this fix into the next release (coming out shortly).  The new code has been a quite a large rewrite so a merge won't be (easily) possible.  But hopefully others can apply it if they are using older versions.
