### ISSUE TITLE
Allowold still allow older dates in same month

### ISSUE THREAD

**Issue by petrivoges** [glad/glDatePicker#16]
When allowold is set I expect that no one is allowed to select an older than today's date, yet, allowold doesn't allow one to pick a date of a previous month. Is there a quick fix for this. I have tried setting a specific startdate or even selected date in the current month but it is not working .

**Comment by glad** [comment]
Hi there,

This will actually be resolved in the next release (which also includes numerious other fixes and features).  The new release will simply not let you set anything beyond the min/max dates and the allowOld flag will be deprecated.

**Comment by petrivoges** [comment]
Thanks for the quick reply. When is your expected date on the new release,
I need to know if I must use another datepicker because we are going live
in less than a month and my manager wont accept this as my solution.
Thanks for the great work you're doing. Love the fact that it is so
lightweight

On Thu, Aug 16, 2012 at 1:31 PM, Gautam Lad notifications@github.comwrote:

> Hi there,
> 
> This will actually be resolved in the next release (which also includes
> numerious other fixes and features). The new release will simply not let
> you set anything beyond the min/max dates and the allowOld flag will be
> deprecated.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/glad/glDatePicker/issues/16#issuecomment-7782884.

## 

Groente
Petri

In need of good news, Ezekiel 18:32 will suffice!

**Comment by glad** [comment]
Well the core of the work is pretty much done and I am hoping to release in the next week or two.  Just writing up some of the docs and examples to go in line with the updated code.

Thanks for the compliments!

**Comment by glad** [comment]
This is addressed in the next build coming out soon.

The allowOld flag is deprecated and isn't available in the next release.

Instead you can specify individual dates (and ranges of dates) that can be selectable.  

See: https://github.com/glad/glDatePicker/pull/18#issuecomment-11650900
