### ISSUE TITLE
First selectable Date

### ISSUE THREAD

**Issue by owendayton** [glad/glDatePicker#19]
Has anyone created a way to have the first selectable date be the current day's date? I really want to use the plugin but need it to not allow selections before the current date.

**Comment by steve228uk** [comment]
Can you not just define the startDate as todays date? That way past dates won't even be available to view.

**Comment by owendayton** [comment]
Tried that but it removed the first of the month as the display date. Actually just figured it out. Just added the following:

```
                    // Test to see if we allow old dates
                    if(!settings.allowOld)
                    {
                        c = (dateTime < startTime) ? "noday":c;
                        c = (dateTime < today) ? "noday":c; //ADDED THIS LINE

                    }
```

**Comment by steve228uk** [comment]
Submit a pull request… though mine is still waiting.

**Comment by glad** [comment]
This is addressed in the next build coming out soon.

You will be able to restrict selection to specific dates.
