### ISSUE TITLE
showTime not working

### ISSUE THREAD

**Issue by activestylus** [glad/glDatePicker#20]
Looking at the source code I should be able to add an hour and minute selector, yet when i specify `{showTime:true}` nothing appears?

**Comment by activestylus** [comment]
Argh.. I was looking at the wrong lib 

In related news, time picker would be awesome :p

**Comment by glad** [comment]
Hah, no worries.  In the new release I'm working on there will be year/month selector however I haven't quite considered time yet.  Though it shouldn't be hard as it will just be two (H,M) or three (H,M,S) additional values returned to you.  I'll look into it.

**Comment by glad** [comment]
Unfortunately this feature will not be available in the next build (or any future builds).

My suggestion would be to use glDatePicker to select dates and then provide another input control to select the time.

This plugin looks like a great compliment to glDatePicker:
https://github.com/jonthornton/jquery-timepicker
