### ISSUE TITLE
Customize width/height of calendar

### ISSUE THREAD

**Issue by pixelfreak** [glad/glDatePicker#23]
There should be a way to customize the width and height of the calendar. It seems very limited that it currently uses the width of the textbox to determine the width of the calendar.

**Comment by pixelfreak** [comment]
Pull request: https://github.com/glad/glDatePicker/pull/24

**Comment by glad** [comment]
The plugin can use a custom element container where the calendar will get rendered into.  Doing this will allow you to use any width/height you want the calendar to be.

The calendar will only default to the input width if the container doesn't exist already.

Please see Step #2 in Usage: http://glad.github.com/glDatePicker/#usage

**Comment by pixelfreak** [comment]
@glad While it is doable with custom container, it is not as convenient/clean as you'll have to add the extra markup + CSS. Being able to specify the width while initializing the calendar is much easier. And if you look at my implementation, the code is also pretty straightforward.

**Comment by threevolve** [comment]
pixelfreak is right. Not only easier, but better. Having to put superfluous markup into every form where the date picker needs to be a certain size is wasteful and not best practice. For the sole purpose of controlling the dimensions of the output, glDatePicker should be handling width and height directly as options.

**Comment by manfe** [comment]
+1 should have height, width and alignment on left or right of the input
