### ISSUE TITLE
Using gldp-id and gldp-target not working

### ISSUE THREAD

**Issue by Stiropor** [glad/glDatePicker#28]
Nothing much to say except this does not work. My code is:

``` html
<input type="text" class="date_ph" gldp-id="calendar_side_wrap" id="calendar_side_wrap" />
<div class="calendar_wrap" gldp-target="calendar_side_wrap"></div>
```

And JS:

``` javascript
$('#calendar_side_wrap').glDatePicker({
    showAlways: true
});
```

It doesn't render calendar in desired DIV. Either there is a bug or something missing in documentation.

**Comment by Pattentrick** [comment]
I have the same issue here. I cant find anything about the "gldp-target" in the source code of the plugin at all.

when i rewrite this part of the code:

self.calendar = $($.find('[gldp-el=' + el.attr('gldp-id') + ' ]'));

to my own element:

self.calendar = $(".my-custom-container");

it works however ... but i have a lot of custom containers. so this workaround is not a solution for me.

**Comment by glad** [comment]
This is resolved.  It was a typo in the guide which showed gldp-target instead of gldp-el.

The correct attribute to use is gldp-el which will point to the element with gldp-id.

Apologies for the mix up.
