### ISSUE TITLE
Lock past dates

### ISSUE THREAD

**Issue by ghost** [glad/glDatePicker#30]
How is it possible to prevent users from selecting dates before current day?

**Comment by glad** [comment]
deepvoid, please see Example #2 http://glad.github.com/glDatePicker/#examples

e.g. This will set the range from "today" to some really large date in the future:

selectableDateRange: [ { from: new Date(), to: new Date(1e15) } ]

**Comment by ghost** [comment]
Hi Glad, I deeply thank you for your help! :-)

And another question: I would like to set a selectable date range coming from current date to 30 days in the future. Is this possible, using the syntax you suggested?

**Comment by glad** [comment]
deepvoid, yes you can.  See the code below on how:

// Create today's date and the future date
var today = new Date();
var future = new Date(today);

// Add 30-days to the future date
future.setDate(today.getDate() + 30);

...
selectableDateRange: [ { from: today, to: future } ]

**Comment by ghost** [comment]
Glad, I don't have words to thank you!!! :-)

Your datePicker is AMAZING!!! :-)

**Comment by glad** [comment]
Thank you for the kind words :)

**Comment by jackworthing** [comment]
Hi,

How is it possible to prevent users from selecting previous Months before current day?

Thanks.

**Comment by RonnieCSE** [comment]
Sir,
I want to disable current_date to  $I++ $date

how is it possible ???
