### ISSUE TITLE
Typo in Changelog on website

### ISSUE THREAD

**Issue by jackocnr** [glad/glDatePicker#32]
Version 1.3 was released after 2.0?

**Comment by glad** [comment]
Heh, nope, definitely not.

It should have been 2012 not 2013.

I'll have it fixed shortly.

Thanks for letting me now :)

**Comment by jackocnr** [comment]
No problem man. Sorry for spamming your issue queue!

Thanks a lot for all the work - it is really appreciated.

**Comment by glad** [comment]
No worries dude, appreciate any and every bit of feedback :)
