### ISSUE TITLE
Selected date shows up in different format than MM/DD/YYYY on PC FF, IE

### ISSUE THREAD

**Issue by taylorkearns** [glad/glDatePicker#38]
When selecting a date from the date picker using Firefox 19 and IE 9 on a VirtualBox Windows 7 PC, the date that appears in the input field is in the more narrative form ("Tuesday, March 26, 2013") instead of the typical "3/26/13."
![Screen Shot](https://f.cloud.github.com/assets/311215/229278/440f7f00-869a-11e2-9b5f-7747ceb9fa9e.png)

**Comment by glad** [comment]
The default implementation on date selection simply uses the client's (browser's) method for returning the date string.

Below is the default callback method when a date is selected:

onClick: (function(el, cell, date, data) {
    el.val(date.toLocaleDateString());
}),

If you want a specific format, you will need to override the onClick callback.

This is shown in example #3 here http://glad.github.com/glDatePicker/#examples

**Comment by taylorkearns** [comment]
Thanks! Apologies, should have read the docs closer.
