### ISSUE TITLE
problem with embedded label elements

### ISSUE THREAD

**Issue by efleming969** [glad/glDatePicker#4]
When using an embedded input with a label, glDatePicker goes into an infinite loop unless you click off the area.

Happens in Chrome 15 and Firefox 4, Not IE8 or IE9

http://jsfiddle.net/efleming969/mYPKq/

**Comment by glad** [comment]
This is addressed in the next build coming out soon.

I've tested the new code against the jsfiddle example provided and it works as expected.

Edit:
A new flag is now provided to allow the calendar to hide when a date is selected.
