### ISSUE TITLE
Swapping the month and day around.

### ISSUE THREAD

**Issue by stompweb** [glad/glDatePicker#7]
Hi,

In the US you have MM/DD/YYYY however in the UK and many other places in the world you have DD/MM/YYYY.

How could the plugin be changed to cater for that please?

Cheers,
Steve

**Comment by glad** [comment]
Hi Steve,

It's not the plugin that does the actual formatting but the onChange callback that allows you to set the bounded textbox to update to whatever value/format.

The Example 6 shows this.  Here's the snippet of code for it.  In this case "target" is referring to the textbox that you are updating on completion and on complete the value will be in YYYY-MM-DD format.

Good luck.

```
<input type="text" id="date6" class="gldp _gldp">

$("#date6").glDatePicker(
{
    onChange: function(target, newDate)
    {
        target.val
        (
            newDate.getFullYear() + "-" +
            (newDate.getMonth() + 1) + "-" +
            newDate.getDate()
        );
    }
});
```

**Comment by stompweb** [comment]
That's great thanks - got it working.

**Comment by zhaabbaa** [comment]
onChange callback _sets_ the field, but how init glDatePicker from the field with 'dd-mm-yyyy' format?

$( ".jgnt_form_date" ).glDatePicker({
        selectedDate: ???

Please help.

**Comment by yafp** [comment]
@glad  
could it be that this doesn't work anymore with v2 of glDatePicker?
Just trying to replace v1.3 with 2.0 and realizing i do get my date displayed in us-format instead of my reformated format (using similar code like above)
